const STYLE_ID = 'dsh-automation-styles'

const CSS_TEXT = String.raw`
.dsh-automation-shell,.dsh-automation-shell *{box-sizing:border-box}
.dsh-automation-shell{width:100%;height:100%;min-height:0;container-name:dsh-automation;container-type:inline-size;overflow:auto;overscroll-behavior:contain;padding:28px clamp(20px,3vw,48px) calc(var(--dsh-composer-height,152px) + 36px);background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font-family:var(--dsw-font-family,system-ui);scrollbar-gutter:stable}
.dsh-automation-conversation-surface{width:100%;height:100%;min-height:0}
.dsh-automation-header{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;max-width:1440px;margin:0 auto 18px}
.dsh-automation-heading{display:flex;min-width:0;align-items:flex-start;gap:14px}.dsh-automation-heading h1{margin:1px 0 3px;font-size:25px;line-height:31px;letter-spacing:-.025em}.dsh-automation-heading p{margin:0;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:20px}
.dsh-automation-logo{display:inline-flex;width:44px;height:44px;flex:none;align-items:center;justify-content:center;border:1px solid color-mix(in srgb,var(--dsw-alias-state-business-primary) 25%,var(--dsw-alias-border-l2));border-radius:14px;background:color-mix(in srgb,var(--dsw-alias-state-business-tertiary) 76%,var(--dsw-alias-bg-base));box-shadow:var(--dsw-shadow-lv1);color:var(--dsw-alias-state-business-primary)}.dsh-automation-logo svg{width:23px;height:23px}
.dsh-automation-kicker{display:block;color:var(--dsw-alias-state-business-primary);font-size:10px;font-weight:700;line-height:15px;letter-spacing:.075em;text-transform:uppercase}
.dsh-automation-shell{padding-bottom:36px}
.dsh-automation-scope{justify-content:space-between}.dsh-automation-scope label{display:flex;min-width:0;align-items:center;gap:7px}.dsh-automation-scope select{min-width:180px;height:30px;padding:4px 28px 4px 9px;border:1px solid var(--dsw-alias-border-l2);border-radius:7px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font:11px/17px var(--dsw-font-family,system-ui)}
.dsh-automation-scope{display:flex;max-width:1440px;align-items:center;gap:22px;margin:0 auto 18px;padding:9px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary);font-size:11px;line-height:17px}.dsh-automation-scope span{display:flex;min-width:0;align-items:center;gap:7px}.dsh-automation-scope strong{color:var(--dsw-alias-label-tertiary);font-weight:600}.dsh-automation-scope code{overflow:hidden;color:var(--dsw-alias-label-secondary);font:11px/17px ui-monospace,SFMono-Regular,Menlo,monospace;text-overflow:ellipsis;white-space:nowrap}
.dsh-automation-button{display:inline-flex;min-height:34px;align-items:center;justify-content:center;gap:7px;padding:6px 13px;border:1px solid transparent;border-radius:9px;font:600 12px/18px var(--dsw-font-family,system-ui);white-space:nowrap;cursor:pointer;transition:background var(--ds-transition-duration-fast,120ms),border-color var(--ds-transition-duration-fast,120ms),color var(--ds-transition-duration-fast,120ms),transform var(--ds-transition-duration-fast,120ms)}.dsh-automation-button svg{width:16px;height:16px}.dsh-automation-button:disabled{cursor:not-allowed;opacity:.45}.dsh-automation-button--primary{border-color:var(--dsw-alias-button-info-fill);background:var(--dsw-alias-button-info-fill);color:var(--dsw-alias-label-primary-foreground);box-shadow:var(--dsw-shadow-lv1)}.dsh-automation-button--primary:hover:not(:disabled){border-color:var(--dsw-alias-button-info-hover);background:var(--dsw-alias-button-info-hover);transform:translateY(-1px)}.dsh-automation-button--ghost{border-color:var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-secondary)}.dsh-automation-button--ghost:hover:not(:disabled){border-color:color-mix(in srgb,var(--dsw-alias-state-business-primary) 38%,var(--dsw-alias-border-l2));background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-state-business-primary)}.dsh-automation-button--danger{border-color:var(--dsw-alias-state-error-primary);background:var(--dsw-alias-state-error-primary);color:var(--dsw-alias-label-primary-foreground)}
.dsh-automation-icon-button{display:inline-flex;width:32px;height:32px;flex:none;align-items:center;justify-content:center;padding:0;border:1px solid transparent;border-radius:8px;background:transparent;color:var(--dsw-alias-label-tertiary);cursor:pointer}.dsh-automation-icon-button:hover:not(:disabled){border-color:var(--dsw-alias-border-l2);background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-state-business-primary)}.dsh-automation-icon-button:disabled{cursor:not-allowed;opacity:.4}
.dsh-automation-stats{display:grid;max-width:1440px;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:0 auto 22px}.dsh-automation-stats>div{position:relative;display:flex;min-height:76px;overflow:hidden;flex-direction:column;justify-content:center;padding:12px 15px;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-layer-1)}.dsh-automation-stats>div:before{position:absolute;top:0;bottom:0;left:0;width:3px;background:var(--dsw-alias-state-business-primary);content:''}.dsh-automation-stats>div.is-attention:before{background:var(--dsw-alias-state-error-primary)}.dsh-automation-stats span{color:var(--dsw-alias-label-tertiary);font-size:10px;font-weight:600;line-height:16px;text-transform:uppercase;letter-spacing:.055em}.dsh-automation-stats strong{overflow:hidden;margin-top:2px;font-size:17px;line-height:23px;text-overflow:ellipsis;white-space:nowrap}.dsh-automation-stats>div:nth-child(-n+2) strong{color:var(--dsw-alias-state-business-primary);font-size:22px}
.dsh-automation-content{display:grid;max-width:1440px;min-height:0;grid-template-columns:minmax(0,1.7fr) minmax(300px,.8fr);align-items:start;gap:18px;margin:0 auto}.dsh-automation-main-column,.dsh-automation-runs-column{min-width:0}.dsh-automation-runs-column{position:sticky;top:0}
.dsh-automation-section-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:10px;padding:0 2px}.dsh-automation-section-heading h2{margin:0;font-size:14px;line-height:20px}.dsh-automation-section-heading p{margin:2px 0 0;color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:17px}
.dsh-automation-card-list{display:flex;flex-direction:column;gap:10px}.dsh-automation-card{padding:16px;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1);box-shadow:var(--dsw-shadow-lv1);transition:border-color var(--ds-transition-duration-fast,120ms),box-shadow var(--ds-transition-duration-fast,120ms)}.dsh-automation-card:hover{border-color:color-mix(in srgb,var(--dsw-alias-state-business-primary) 28%,var(--dsw-alias-border-l2));box-shadow:var(--dsw-shadow-lv2)}
.dsh-automation-card-top{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.dsh-automation-card-title{display:flex;min-width:0;align-items:flex-start;gap:10px}.dsh-automation-card-title>div{min-width:0}.dsh-automation-card-title h3{overflow:hidden;margin:0 0 6px;font-size:14px;line-height:20px;text-overflow:ellipsis;white-space:nowrap}.dsh-automation-card-icon{display:inline-flex;width:34px;height:34px;flex:none;align-items:center;justify-content:center;border-radius:10px;background:var(--dsw-alias-state-business-tertiary);color:var(--dsw-alias-state-business-primary)}.dsh-automation-card-icon svg{width:18px;height:18px}.dsh-automation-revision{padding:2px 6px;border-radius:5px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-tertiary);font:10px/15px ui-monospace,SFMono-Regular,Menlo,monospace}
.dsh-automation-card-badges{display:flex;flex-wrap:wrap;align-items:center;gap:5px}.dsh-automation-badge,.dsh-automation-permission-badge{display:inline-flex;align-items:center;gap:5px;padding:2px 7px;border:1px solid var(--dsw-alias-border-l2);border-radius:999px;color:var(--dsw-alias-label-secondary);font-size:10px;font-weight:600;line-height:15px}.dsh-automation-status-dot{width:6px;height:6px;border-radius:50%;background:var(--dsw-alias-label-tertiary)}.dsh-automation-badge--active{border-color:color-mix(in srgb,var(--dsw-alias-state-success-primary) 30%,var(--dsw-alias-border-l2));background:var(--dsw-alias-state-success-tertiary);color:var(--dsw-alias-state-success-primary)}.dsh-automation-badge--active .dsh-automation-status-dot{background:var(--dsw-alias-state-success-primary);box-shadow:0 0 0 3px color-mix(in srgb,var(--dsw-alias-state-success-primary) 12%,transparent)}.dsh-automation-badge--paused{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-tertiary)}.dsh-automation-permission-badge svg{width:12px;height:12px}
.dsh-automation-health-badge{display:inline-flex;padding:2px 7px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-error-primary) 35%,var(--dsw-alias-border-l2));border-radius:999px;background:var(--dsw-alias-state-error-secondary);color:var(--dsw-alias-state-error-primary);font-size:10px;font-weight:650;line-height:15px}.dsh-automation-health{display:flex;align-items:flex-start;gap:7px;margin:-3px 0 12px;padding:8px 9px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-error-primary) 30%,var(--dsw-alias-border-l2));border-radius:8px;background:var(--dsw-alias-state-error-secondary);color:var(--dsw-alias-state-error-primary);font-size:10px;line-height:16px}.dsh-automation-health svg{width:14px;height:14px;flex:none}
.dsh-automation-prompt{display:-webkit-box;overflow:hidden;margin:13px 0 12px;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:19px;-webkit-box-orient:vertical;-webkit-line-clamp:2}.dsh-automation-schedule-line{display:flex;min-width:0;align-items:center;gap:7px;padding:8px 9px;border-radius:8px;background:var(--dsw-alias-state-business-tertiary);color:var(--dsw-alias-state-business-primary);font-size:11px;line-height:17px}.dsh-automation-schedule-line svg{width:14px;height:14px;flex:none}.dsh-automation-schedule-line strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dsh-automation-schedule-line span{margin-left:auto;color:var(--dsw-alias-label-secondary);font:10px/16px ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap}
.dsh-automation-prompt-details{margin:-7px 0 12px;color:var(--dsw-alias-label-secondary);font-size:10px;line-height:16px}.dsh-automation-prompt-details summary{width:max-content;color:var(--dsw-alias-state-business-primary);font-weight:650;cursor:pointer}.dsh-automation-prompt-details pre{max-height:320px;overflow:auto;margin:8px 0 0;padding:10px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font:11px/18px ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;overflow-wrap:anywhere}
.dsh-automation-card-times{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.dsh-automation-card-times>div{display:flex;align-items:center;justify-content:space-between;gap:8px;padding-right:10px;border-right:1px solid var(--dsw-alias-border-l2)}.dsh-automation-card-times>div:last-child{padding-right:0;border-right:0}.dsh-automation-card-times dt{color:var(--dsw-alias-label-tertiary);font-size:10px;line-height:16px}.dsh-automation-card-times dd{display:flex;align-items:center;gap:5px;margin:0;color:var(--dsw-alias-label-secondary);font-size:11px;font-weight:600;line-height:16px}.dsh-automation-mini-dot{width:6px;height:6px;border-radius:50%;background:var(--dsw-alias-label-tertiary)}.dsh-automation-mini-dot--succeeded{background:var(--dsw-alias-state-success-primary)}.dsh-automation-mini-dot--failed,.dsh-automation-mini-dot--interrupted{background:var(--dsw-alias-state-error-primary)}.dsh-automation-mini-dot--running,.dsh-automation-mini-dot--queued{background:var(--dsw-alias-state-business-primary)}
.dsh-automation-card-actions{display:flex;align-items:center;justify-content:flex-end;gap:7px;padding-top:12px;border-top:1px solid var(--dsw-alias-border-l2)}.dsh-automation-delete-confirm{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-error-primary) 35%,var(--dsw-alias-border-l2));border-radius:9px;background:var(--dsw-alias-state-error-secondary)}.dsh-automation-delete-confirm>div:first-child{display:flex;flex-direction:column}.dsh-automation-delete-confirm strong{font-size:11px;line-height:17px}.dsh-automation-delete-confirm span{color:var(--dsw-alias-label-secondary);font-size:10px;line-height:15px}.dsh-automation-delete-confirm>div:last-child{display:flex;gap:6px}
.dsh-automation-run-list{display:flex;overflow:hidden;flex-direction:column;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1);box-shadow:var(--dsw-shadow-lv1)}.dsh-automation-run{padding:13px 14px;border-bottom:1px solid var(--dsw-alias-border-l2)}.dsh-automation-run:last-child{border-bottom:0}.dsh-automation-run-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.dsh-automation-run-head>div{display:flex;min-width:0;flex-direction:column}.dsh-automation-run-name{overflow:hidden;font-size:12px;font-weight:650;line-height:18px;text-overflow:ellipsis;white-space:nowrap}.dsh-automation-run-trigger,.dsh-automation-run-head time{color:var(--dsw-alias-label-tertiary);font-size:10px;line-height:15px;white-space:nowrap}.dsh-automation-run-status{display:inline-flex;align-items:center;gap:5px;margin-top:8px;color:var(--dsw-alias-label-secondary);font-size:10px;font-weight:650;line-height:16px}.dsh-automation-run-status svg{width:13px;height:13px}.dsh-automation-run-status--succeeded{color:var(--dsw-alias-state-success-primary)}.dsh-automation-run-status--failed,.dsh-automation-run-status--interrupted{color:var(--dsw-alias-state-error-primary)}.dsh-automation-run-status--running,.dsh-automation-run-status--queued{color:var(--dsw-alias-state-business-primary)}.dsh-automation-run-status--running svg{animation:dsh-automation-spin 1.6s linear infinite}.dsh-automation-run p{display:-webkit-box;overflow:hidden;margin:7px 0 0;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:17px;-webkit-box-orient:vertical;-webkit-line-clamp:3}.dsh-automation-run p.is-error{color:var(--dsw-alias-state-error-primary)}.dsh-automation-session-id{display:block;overflow:hidden;margin-top:6px;color:var(--dsw-alias-label-tertiary);font:9px/14px ui-monospace,SFMono-Regular,Menlo,monospace;text-overflow:ellipsis;white-space:nowrap}
.dsh-automation-run-phase,.dsh-automation-run-model{display:block;margin-top:4px;color:var(--dsw-alias-label-tertiary);font-size:9px;line-height:14px}.dsh-automation-run-phase{color:var(--dsw-alias-state-business-primary);font-weight:650}
.dsh-automation-empty,.dsh-automation-runs-empty{display:flex;min-height:250px;flex-direction:column;align-items:center;justify-content:center;padding:34px;border:1px dashed var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1);text-align:center}.dsh-automation-empty>span{display:inline-flex;width:48px;height:48px;align-items:center;justify-content:center;border-radius:15px;background:var(--dsw-alias-state-business-tertiary);color:var(--dsw-alias-state-business-primary)}.dsh-automation-empty h3{margin:13px 0 4px;font-size:14px}.dsh-automation-empty p{max-width:440px;margin:0 0 17px;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:18px}.dsh-automation-runs-empty{min-height:140px;color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:18px}
.dsh-automation-create{max-width:1440px;margin:0 auto 18px;padding:18px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-business-primary) 28%,var(--dsw-alias-border-l2));border-radius:14px;background:color-mix(in srgb,var(--dsw-alias-state-business-tertiary) 38%,var(--dsw-alias-bg-layer-1));box-shadow:var(--dsw-shadow-lv1)}.dsh-automation-create-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:16px}.dsh-automation-create-heading h2{margin:2px 0 2px;font-size:16px;line-height:22px}.dsh-automation-create-heading p{margin:0;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:17px}.dsh-automation-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.dsh-automation-field--wide{grid-column:1/-1}.dsh-automation-field{display:flex;min-width:0;flex-direction:column;gap:6px}.dsh-automation-field>span:first-child,.dsh-automation-fieldset legend{color:var(--dsw-alias-label-secondary);font-size:10px;font-weight:650;line-height:16px}.dsh-automation-field input,.dsh-automation-field textarea{width:100%;min-width:0;padding:8px 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;outline:none;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font:12px/18px var(--dsw-font-family,system-ui)}.dsh-automation-field input{height:36px}.dsh-automation-field textarea{min-height:88px;resize:vertical}.dsh-automation-field input:focus,.dsh-automation-field textarea:focus{border-color:var(--dsw-alias-state-business-primary);box-shadow:0 0 0 3px color-mix(in srgb,var(--dsw-alias-state-business-primary) 12%,transparent)}.dsh-automation-field input::placeholder,.dsh-automation-field textarea::placeholder{color:var(--dsw-alias-label-dimmed)}
.dsh-automation-fieldset{min-width:0;margin:0;padding:0;border:0}.dsh-automation-fieldset legend{margin-bottom:6px;padding:0}.dsh-automation-segmented{display:inline-grid;grid-template-columns:repeat(4,minmax(80px,1fr));gap:3px;padding:3px;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;background:var(--dsw-alias-bg-layer-2)}.dsh-automation-segmented button,.dsh-automation-weekdays button{height:29px;padding:3px 9px;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary);font:600 10px/16px var(--dsw-font-family,system-ui);cursor:pointer}.dsh-automation-segmented button:hover,.dsh-automation-weekdays button:hover{background:var(--dsw-alias-interactive-bg-hover)}.dsh-automation-segmented button.is-selected,.dsh-automation-weekdays button.is-selected{background:var(--dsw-alias-bg-base);box-shadow:var(--dsw-shadow-lv1);color:var(--dsw-alias-state-business-primary)}.dsh-automation-schedule-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:10px}.dsh-automation-weekdays{grid-column:1/-1}.dsh-automation-weekdays>div{display:flex;flex-wrap:wrap;gap:4px}.dsh-automation-weekdays button{min-width:44px;border:1px solid var(--dsw-alias-border-l2)}.dsh-automation-weekdays button.is-selected{border-color:color-mix(in srgb,var(--dsw-alias-state-business-primary) 38%,var(--dsw-alias-border-l2));background:var(--dsw-alias-state-business-tertiary)}.dsh-automation-inline-input{display:flex;align-items:center;gap:8px}.dsh-automation-inline-input input{max-width:150px}.dsh-automation-inline-input>span{color:var(--dsw-alias-label-secondary);font-size:11px}
.dsh-automation-segmented--two{grid-template-columns:repeat(2,minmax(130px,1fr))}.dsh-automation-model-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:10px}.dsh-automation-model-hint{margin:8px 0 0;color:var(--dsw-alias-label-secondary);font-size:10px;line-height:16px}
.dsh-automation-schedule-preview{display:flex;grid-column:1/-1;align-items:center;gap:7px;padding:8px 10px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-business-primary) 24%,var(--dsw-alias-border-l2));border-radius:8px;background:var(--dsw-alias-state-business-tertiary);color:var(--dsw-alias-state-business-primary);font-size:11px;line-height:17px}.dsh-automation-schedule-preview svg{width:14px;height:14px;flex:none}
.dsh-automation-permission-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.dsh-automation-permission-grid label{display:flex;min-width:0;align-items:flex-start;gap:9px;padding:11px;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;background:var(--dsw-alias-bg-base);cursor:pointer}.dsh-automation-permission-grid label.is-selected{border-color:var(--dsw-alias-state-business-primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-state-business-primary) 10%,transparent)}.dsh-automation-permission-grid input{position:absolute;opacity:0;pointer-events:none}.dsh-automation-permission-grid svg{width:17px;height:17px;flex:none;color:var(--dsw-alias-state-business-primary)}.dsh-automation-permission-grid label>span{display:flex;min-width:0;flex-direction:column}.dsh-automation-permission-grid strong{font-size:11px;line-height:17px}.dsh-automation-permission-grid small{color:var(--dsw-alias-label-secondary);font-size:10px;line-height:15px}
.dsh-automation-form-footer{display:flex;align-items:center;justify-content:flex-end;gap:12px;margin-top:15px;padding-top:13px;border-top:1px solid var(--dsw-alias-border-l2)}.dsh-automation-form-error{flex:1;color:var(--dsw-alias-state-error-primary);font-size:11px;line-height:17px}.dsh-automation-inline-error{display:flex;max-width:1440px;align-items:center;gap:8px;margin:0 auto 14px;padding:9px 11px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-error-primary) 32%,var(--dsw-alias-border-l2));border-radius:9px;background:var(--dsw-alias-state-error-secondary);color:var(--dsw-alias-state-error-primary);font-size:11px;line-height:17px}.dsh-automation-inline-error svg{width:15px;height:15px;flex:none}
.dsh-automation-migration{display:flex;max-width:1440px;align-items:center;gap:8px;margin:0 auto 14px;padding:9px 11px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-success-primary) 30%,var(--dsw-alias-border-l2));border-radius:9px;background:var(--dsw-alias-state-success-tertiary);color:var(--dsw-alias-state-success-primary);font-size:11px;line-height:17px}.dsh-automation-migration svg{width:15px;height:15px;flex:none}
.dsh-automation-centered{display:flex;min-height:420px;flex-direction:column;align-items:center;justify-content:center;gap:9px;text-align:center;color:var(--dsw-alias-label-secondary);font-size:12px}.dsh-automation-centered h2{margin:3px 0 0;color:var(--dsw-alias-label-primary);font-size:15px}.dsh-automation-centered p{max-width:480px;margin:0 0 8px;color:var(--dsw-alias-label-secondary)}.dsh-automation-loader,.dsh-automation-error-icon{display:inline-flex;width:46px;height:46px;align-items:center;justify-content:center;border-radius:14px;background:var(--dsw-alias-state-business-tertiary);color:var(--dsw-alias-state-business-primary)}.dsh-automation-loader svg{animation:dsh-automation-spin 1.6s linear infinite}.dsh-automation-error-icon{background:var(--dsw-alias-state-error-secondary);color:var(--dsw-alias-state-error-primary)}
.dsh-automation-session-id{max-width:100%;padding:0;border:0;background:transparent;color:var(--dsw-alias-state-business-primary);text-align:left;cursor:pointer}.dsh-automation-session-id:hover{text-decoration:underline}.dsh-automation-session-id--archived{color:var(--dsw-alias-label-tertiary);cursor:default}.dsh-automation-session-id--archived:hover{text-decoration:none}
.dsh-automation-error-code{display:block;width:max-content;margin-top:6px;padding:2px 6px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-error-primary) 28%,var(--dsw-alias-border-l2));border-radius:5px;background:var(--dsw-alias-state-error-secondary);color:var(--dsw-alias-state-error-primary);font:9px/14px ui-monospace,SFMono-Regular,Menlo,monospace}.dsh-automation-run-review{display:inline-flex;align-items:center;gap:4px;margin-top:7px;padding:2px 7px;border:1px solid var(--dsw-alias-border-l2);border-radius:6px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-secondary);font:600 9px/14px var(--dsw-font-family,system-ui);cursor:pointer}.dsh-automation-run-review svg{width:11px;height:11px}.dsh-automation-run-review:hover:not(:disabled){border-color:color-mix(in srgb,var(--dsw-alias-state-business-primary) 38%,var(--dsw-alias-border-l2));color:var(--dsw-alias-state-business-primary)}.dsh-automation-run-review:disabled{cursor:not-allowed;opacity:.45}
.dsh-automation-shell button:focus-visible,.dsh-automation-shell input:focus-visible,.dsh-automation-shell textarea:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px}
@keyframes dsh-automation-spin{to{transform:rotate(360deg)}}
@media(max-width:1100px){.dsh-automation-content{grid-template-columns:1fr}.dsh-automation-runs-column{position:static}.dsh-automation-run-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.dsh-automation-run:nth-child(odd){border-right:1px solid var(--dsw-alias-border-l2)}.dsh-automation-run:nth-last-child(-n+2){border-bottom:0}}
@media(max-width:760px){.dsh-automation-shell{padding:18px 14px calc(var(--dsh-composer-height,152px) + 24px)}.dsh-automation-header{align-items:center}.dsh-automation-heading p{display:none}.dsh-automation-logo{width:38px;height:38px;border-radius:12px}.dsh-automation-stats{grid-template-columns:1fr 1fr}.dsh-automation-scope{align-items:flex-start;flex-direction:column;gap:4px}.dsh-automation-form-grid,.dsh-automation-schedule-fields,.dsh-automation-permission-grid,.dsh-automation-model-grid{grid-template-columns:1fr}.dsh-automation-segmented{width:100%;grid-template-columns:1fr 1fr}.dsh-automation-card-times{grid-template-columns:1fr}.dsh-automation-card-times>div{padding-right:0;border-right:0}.dsh-automation-run-list{grid-template-columns:1fr}.dsh-automation-run:nth-child(odd){border-right:0}.dsh-automation-run:nth-last-child(2){border-bottom:1px solid var(--dsw-alias-border-l2)}}
@media(max-width:480px){.dsh-automation-header{align-items:flex-start;flex-direction:column}.dsh-automation-header>.dsh-automation-button{width:100%}.dsh-automation-heading h1{font-size:21px}.dsh-automation-stats{gap:7px}.dsh-automation-stats>div{min-height:68px;padding:10px 12px}.dsh-automation-card{padding:13px}.dsh-automation-schedule-line{align-items:flex-start;flex-wrap:wrap}.dsh-automation-schedule-line span{width:100%;margin-left:21px}.dsh-automation-card-actions{display:grid;grid-template-columns:1fr 1fr}.dsh-automation-card-actions>.dsh-automation-icon-button{position:absolute;right:28px}.dsh-automation-delete-confirm{align-items:stretch;flex-direction:column}.dsh-automation-delete-confirm>div:last-child{justify-content:flex-end}.dsh-automation-create{padding:14px}.dsh-automation-create-heading{flex-direction:column}.dsh-automation-create-heading>.dsh-automation-button{display:none}}
@container dsh-automation (max-width:1100px){.dsh-automation-content{grid-template-columns:1fr}.dsh-automation-runs-column{position:static}.dsh-automation-run-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.dsh-automation-run:nth-child(odd){border-right:1px solid var(--dsw-alias-border-l2)}.dsh-automation-run:nth-last-child(-n+2){border-bottom:0}}
@container dsh-automation (max-width:760px){.dsh-automation-shell{padding:18px 14px 24px}.dsh-automation-header{align-items:center}.dsh-automation-heading p{display:none}.dsh-automation-logo{width:38px;height:38px;border-radius:12px}.dsh-automation-stats{grid-template-columns:1fr 1fr}.dsh-automation-scope{align-items:flex-start;flex-direction:column;gap:4px}.dsh-automation-form-grid,.dsh-automation-schedule-fields,.dsh-automation-permission-grid,.dsh-automation-model-grid{grid-template-columns:1fr}.dsh-automation-segmented{width:100%;grid-template-columns:1fr 1fr}.dsh-automation-card-times{grid-template-columns:1fr}.dsh-automation-card-times>div{padding-right:0;border-right:0}.dsh-automation-run-list{grid-template-columns:1fr}.dsh-automation-run:nth-child(odd){border-right:0}.dsh-automation-run:nth-last-child(2){border-bottom:1px solid var(--dsw-alias-border-l2)}}
@container dsh-automation (max-width:480px){.dsh-automation-header{align-items:flex-start;flex-direction:column}.dsh-automation-header>.dsh-automation-button{width:100%}.dsh-automation-heading h1{font-size:21px}.dsh-automation-stats{gap:7px}.dsh-automation-stats>div{min-height:68px;padding:10px 12px}.dsh-automation-card{padding:13px}.dsh-automation-schedule-line{align-items:flex-start;flex-wrap:wrap}.dsh-automation-schedule-line span{width:100%;margin-left:21px}.dsh-automation-card-actions{display:grid;grid-template-columns:1fr 1fr}.dsh-automation-card-actions>.dsh-automation-icon-button{position:absolute;right:28px}.dsh-automation-delete-confirm{align-items:stretch;flex-direction:column}.dsh-automation-delete-confirm>div:last-child{justify-content:flex-end}.dsh-automation-create{padding:14px}.dsh-automation-create-heading{flex-direction:column}.dsh-automation-create-heading>.dsh-automation-button{display:none}}
@media(prefers-reduced-motion:reduce){.dsh-automation-button,.dsh-automation-card{transition:none}.dsh-automation-loader svg,.dsh-automation-run-status--running svg{animation:none}}
.dsh-automation-field select{width:100%;min-width:0;height:36px;padding:8px 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;outline:none;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font:12px/18px var(--dsw-font-family,system-ui)}.dsh-automation-field select:focus{border-color:var(--dsw-alias-state-business-primary);box-shadow:0 0 0 3px color-mix(in srgb,var(--dsw-alias-state-business-primary) 12%,transparent)}
.dsh-automation-shell{padding-bottom:36px}
@media(max-width:760px){.dsh-automation-shell{padding-bottom:24px}}
.dsh-automation-conversation-surface .dsh-automation-shell{padding-bottom:calc(var(--dsh-composer-height,152px) + 36px)}
`

/** Install namespaced token-only styles and remove them when the plugin unloads. */
export function installStyles(): () => void {
  const existing = document.getElementById(STYLE_ID)
  if (existing !== null) return () => undefined
  const style = document.createElement('style')
  style.id = STYLE_ID
  style.textContent = CSS_TEXT
  document.head.append(style)
  return () => { style.remove() }
}
